### ISSUE TITLE
There is something wrong in the GT

### ISSUE THREAD

**Issue by luckcodingdog** [xiexh20/CHORE#6]
Thanks for your interesting work.
I have tried to test on the BEHAVE dataset with CHORE.
But i found there is some thing wrong in the dataset.
For some frames, the joint values of k1.color.json are all 0.
For example, the frame of Date03/Date03_Sub03_backpack_back/t0029.000/k1.color.json.
Could you check the GT and give me some advice?

**Comment by xiexh20** [comment]
Hi, thanks for your interest

This is expected. 
k1.color.json contains openpose detections. if it is all zero, it means one of the following:
1. Openpose failed to detecte any person.
2. openpose detected multiple person in the image, but it was not possible to find the correct foreground person automatically. 
3. the openpose detection has too low confidence

in all these cases, the predictions are set to zeros in order to prevent noise being sent to the later data processing, see our BEHAVE paper for data processing details [here](http://virtualhumans.mpi-inf.mpg.de/behave)

**Comment by luckcodingdog** [comment]
Hi, @xiexh20 Thanks for your reply.
I got your explaination about all zeros for some frame.
But i want to do the evaluation with CHORE on the behave dataset.
There is one question: if there is no joint information for some frame, i willn't get the prediction for the frame.
I have checked the behave code about evaluation:
https://github.com/xiexh20/behave-dataset/blob/55b3e6c0801c8f60a2e93228e810b16d99205329/challenges/evaluate_human.py#L38
The number of prediction of mine is unequal to the number of gt.
But I have checked your submition, there is no the question as mine.

**Comment by xiexh20** [comment]
Hi,

Yes, the human recon track will check the number of predictions and requires it is the same as GT. This is because for human recon, you usually don't need to use the 2d keypoints to do 3d predictions, which is the case in my submission. This is more strict than joint recon track. 

In joint recon, sometimes it is simply not possible to obtain recon. e.g. human or object is heavily occluded. Hence it is allowed that the number of prediction does not match the number of GT.

**Comment by luckcodingdog** [comment]
Thanks, brother! (谢了，铁子)
